# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2

jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:16

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    environment:
      IMAGE_NAME: ugmarket

    working_directory: ~/ugmarket

    steps:
      - checkout

      - run:
          name: Get commit SHA from git
          command: |
            echo "export COMMIT_ID=$(git rev-parse --short HEAD)" >> $BASH_ENV

      - run:
          name: Setup Env
          command: |
            echo 'export IMAGE_NAME=ugmarket' >> $BASH_ENV
            source $BASH_ENV
            echo $COMMIT_ID
            npm install

      - setup_remote_docker:
          docker_layer_caching: true

      - run:
          name: Build Docker image
          command: |
            docker build --build-arg=SERVICE_NAME=$IMAGE_NAME --platform linux/amd64 -t $DOCKER_USERNAME/$IMAGE_NAME .
            docker tag $DOCKER_USERNAME/$IMAGE_NAME  $DOCKER_USERNAME/$IMAGE_NAME:$COMMIT_ID

      - run:
          name: Push Docker Image
          command: |
            echo "$DOCKER_PWD" | docker login -u "$DOCKER_USERNAME" --password-stdin
            docker push $DOCKER_USERNAME/$IMAGE_NAME:$COMMIT_ID

      - add_ssh_keys:
          fingerprints:
            - "SHA256:xbZ+lXdLpdvcoYj8X8X6huA/Z71TBVg+DErTqiooB4w"

      - run:
          name: Debug SSH
          command: |
            ssh -vvv -o StrictHostKeyChecking=no $DO_USER@$DO_IP -p $SSH_PORT "echo 'Testing connection'"

      - run:
          name: Deploy Code
          command: |
            ssh -o StrictHostKeyChecking=no $DO_USER@$DO_IP -p $SSH_PORT "
              cd app && 
              export MYSQL_HOST=$MYSQL_HOST &&
              export IMAGE_TAG=$COMMIT_ID &&
              export IMAGE_NAME=$IMAGE_NAME &&
              ./do_deploy.sh
            "
 